server:
  port: 8080
logging:
  level:
    com:
      rum:
        xianfeng:
          XianfengApplication: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xianfeng?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: winhulin